flasher:
    # Default notification library (e.g., 'flasher', 'toastr', 'noty', etc.)
    # themes: flasher, crystal, emerald, sapphire
    default: theme.flasher

    # Path to the main JavaScript file of PHPFlasher
    main_script: '/vendor/flasher/flasher.min.js'

    # Path to the stylesheets for PHPFlasher notifications
    styles:
        - '/vendor/flasher/flasher.min.css'

    # Enable translation of PHPFlasher messages using Symfony's translator service
    translate: true

    # Automatically inject PHPFlasher assets in HTML response
    inject_assets: true

    # Global options
    options:
        # timeout in milliseconds
        timeout: 600000
        position: 'top-right'

    # Map Symfony session keys to PHPFlasher notification types
    flash_bag:
        success: ['success']
        error: ['error', 'danger']
        warning: ['warning', 'alarm']
        info: ['info', 'notice', 'alert']

    # Criteria to filter displayed notifications (limit, types)
    filter:
        # Limit number of displayed notifications
        # limit: 5

    plugins:
        theme.amazon:
            scripts: ['/vendor/flasher/themes/amazon/amazon.min.js']
            styles:
                - '/vendor/flasher/flasher.min.css'
                - '/vendor/flasher/themes/amazon/amazon.min.css'

        theme.amber:
            scripts: ['/vendor/flasher/themes/amber/amber.min.js']
            styles:
                - '/vendor/flasher/flasher.min.css'
                - '/vendor/flasher/themes/amber/amber.min.css'

        theme.jade:
            scripts: ['/vendor/flasher/themes/jade/jade.min.js']
            styles:
                - '/vendor/flasher/flasher.min.css'
                - '/vendor/flasher/themes/jade/jade.min.css'

        theme.crystal:
            scripts: ['/vendor/flasher/themes/crystal/crystal.min.js']
            styles:
                - '/vendor/flasher/flasher.min.css'
                - '/vendor/flasher/themes/crystal/crystal.min.css'

        theme.emerald:
            scripts: ['/vendor/flasher/themes/emerald/emerald.min.js']
            styles:
                - '/vendor/flasher/flasher.min.css'
                - '/vendor/flasher/themes/emerald/emerald.min.css'

        theme.sapphire:
            scripts: ['/vendor/flasher/themes/sapphire/sapphire.min.js']
            styles:
                - '/vendor/flasher/flasher.min.css'
                - '/vendor/flasher/themes/sapphire/sapphire.min.css'

        theme.ruby:
            scripts: ['/vendor/flasher/themes/ruby/ruby.min.js']
            styles:
                - '/vendor/flasher/flasher.min.css'
                - '/vendor/flasher/themes/ruby/ruby.min.css'

        theme.onyx:
            scripts: ['/vendor/flasher/themes/onyx/onyx.min.js']
            styles:
                - '/vendor/flasher/flasher.min.css'
                - '/vendor/flasher/themes/onyx/onyx.min.css'

        theme.neon:
            scripts: ['/vendor/flasher/themes/neon/neon.min.js']
            styles:
                - '/vendor/flasher/flasher.min.css'
                - '/vendor/flasher/themes/neon/neon.min.css'

        theme.aurora:
            scripts: ['/vendor/flasher/themes/aurora/aurora.min.js']
            styles:
                - '/vendor/flasher/flasher.min.css'
                - '/vendor/flasher/themes/aurora/aurora.min.css'

        theme.minimal:
            scripts: ['/vendor/flasher/themes/minimal/minimal.min.js']
            styles:
                - '/vendor/flasher/flasher.min.css'
                - '/vendor/flasher/themes/minimal/minimal.min.css'

        theme.material:
            scripts: ['/vendor/flasher/themes/material/material.min.js']
            styles:
                - '/vendor/flasher/flasher.min.css'
                - '/vendor/flasher/themes/material/material.min.css'

        theme.google:
            scripts: ['/vendor/flasher/themes/google/google.min.js']
            styles:
                - '/vendor/flasher/flasher.min.css'
                - '/vendor/flasher/themes/google/google.min.css'

        theme.ios:
            scripts: ['/vendor/flasher/themes/ios/ios.min.js']
            styles:
                - '/vendor/flasher/flasher.min.css'
                - '/vendor/flasher/themes/ios/ios.min.css'

        theme.slack:
            scripts: ['/vendor/flasher/themes/slack/slack.min.js']
            styles:
                - '/vendor/flasher/flasher.min.css'
                - '/vendor/flasher/themes/slack/slack.min.css'

        theme.facebook:
            scripts: ['/vendor/flasher/themes/facebook/facebook.min.js']
            styles:
                - '/vendor/flasher/flasher.min.css'
                - '/vendor/flasher/themes/facebook/facebook.min.css'
