name: Auto Closer PR

on:
  pull_request_target:
    types: [ opened ]

jobs:
  run:
    name: 🤖 PR Auto-Closure
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: |
            Hi there 👋,

            First off, thanks for your effort! 🎉 Unfortunately, this repository is read-only because it's split from our primary monorepo repository.

            🙏 We kindly ask if you could direct your valuable contribution to our main repository at https://github.com/php-flasher/php-flasher.

            Once you've moved your contribution there, we'll review it and provide feedback. 🕵️‍♂️

            Thanks again for your understanding and cooperation. We really appreciate it! 🙌
