source 'https://rubygems.org'

gem 'jekyll'
gem 'csv'
gem 'bigdecimal'

group :jekyll_plugins do
  gem 'jekyll-sitemap'
  gem 'jekyll-redirect-from'
  gem 'jekyll-seo-tag'
end

gem "webrick", "~> 1.8"
